const categoriesList = {
  rock: 'Rock',
  pop: 'Pop',
  jazz: 'Jazz',
  blues: 'Blues',
  country: 'Country',
  metal: 'Metal',
  hiphop: 'Hip-Hop',
  rap: 'Rap',
  reggae: 'Reggae',
  classical: 'Classical',
  electronic: 'Electronic',
  dance: 'Dance',
  rnb: 'R&B',
  soul: 'Soul',
  funk: 'Funk',
  punk: 'Punk',
  alternative: 'Alternative',
  indie: 'Indie',
  folk: 'Folk',
  latin: 'Latin',
  world: 'World',
  other: 'Other',
  vocaloid: 'Vocaloid',
  soundtrack: 'Soundtrack',
  instrumental: 'Instrumental',
  ambient: 'Ambient',
  gaming: 'Gaming',
  anime: 'Anime',
  movies_tv: 'Movies & TV',
  chiptune: 'Chiptune',
  lofi: 'Lofi',
  kpop: 'K-pop',
  jpop: 'J-pop',
};

export default categoriesList;
