version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=noteblockworldpassword
      - MONGO_INITDB_DATABASE=noteblockworld
      - MONGO_INITDB_ROOT_USERNAME=noteblockworlduser

volumes:
  mongodb_data:
