services:
  mongodb:
    container_name: opennoteworld-mongodb-dev
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=noteblockworldpassword
      - MONGO_INITDB_DATABASE=noteblockworld
      - MONGO_INITDB_ROOT_USERNAME=noteblockworlduser

  minio:
    container_name: minio
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
volumes:
  mongodb_data:
  minio_data:
