services:
  mongodb:
    container_name: opennoteworld-mongodb-dev
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=noteblockworldpassword
      - MONGO_INITDB_DATABASE=noteblockworld
      - MONGO_INITDB_ROOT_USERNAME=noteblockworlduser

  maildev:
    container_name: opennoteworld-maildev-dev
    image: maildev/maildev
    ports:
      - '1080:1080' # Web Interface
      - '1025:1025' # SMTP Server
      # to use the maildev container, you need to set the following environment variables in your application:
      # MAIL_TRANSPORT=smtp://maildev:1025 or MAIL_TRANSPORT=smtp://localhost:1025
      # MAIL_FROM="Example <noreply@noteblock.world>"
      # 
      # You can also use the maildev web interface to view sent emails at http://localhost:1080

  minio:
    container_name: minio
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
      # You can access the MinIO web interface at http://localhost:9000

  mc:
    container_name: minio-client
    image: minio/mc
    entrypoint: ['/bin/sh', '-c']
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: >
      -c '
      while ! mc alias set minio http://minio:9000 minioadmin minioadmin; do
        echo "Waiting for MinIO to be available..."
        sleep 2
      done &&
      mc mb minio/noteblockworld-songs &&
      mc mb minio/noteblockworld-thumbs
      '

volumes:
  mongodb_data:
  minio_data:
