"use client";

import { useState } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DefaultLayout from "../components/common/DefaultLayout";
import Sidebar from "../components/common/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultLayout
          isSidebarOpen={sidebarOpen}
          setSidebarOpen={(open: boolean) => setSidebarOpen(open)}
        >
          {children}
        </DefaultLayout>
      </body>
    </html>
  );
}
