import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from '../lib/registry';
import NextTopLoader from 'nextjs-toploader';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='min-h-screen'>
      <body className={lato.className + ' min-h-screen bg-zinc-900'}>
        <NextTopLoader
          showSpinner={false}
          crawlSpeed={700}
          speed={700}
          easing='cubic-bezier(0.16, 1, 0.3, 1)' // easeOutExpo
          height={3}
        />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
